add refusal analyzer
monalabs/mona-openai pull request #24
Opened 2023-08-10 19:46 UTC by TalzMona

Add a new analyzer which return the probability that a given answer is a refusal answer

2023-08-14 11:12 UTC, itaiMona requested changes
Nothing major besides the need for tests - let's review one more time after that.

2023-08-14 11:12 UTC, itaiMona commented on tests/test_chat_completion.py
> +    "refusal_probability": (0.18,),
I'd expect a specific test file for the new analyzer, testing just that analyzer and the full flow, with some obvious examples, and checking for high / low probabilities - not exact ones.

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/endpoints/endpoint_wrapping.py
> +    def _get_full_profainty_analysis(
Are you using a specific tool for all these reformattings? Maybe we add this as automation in the repo?

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +Functionality for computing probability that a given GAI response is actually a refusal
I don't like "GAI" in this context. Too broad. I would say "textual"

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +answer (which means the model can't or not allowed to answer the given prompt).
"can't or won't answer the given prompt"

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +from huggingface_hub.utils._errors import RepositoryNotFoundError
This doesn't require a new "requirement" in requirements.text?

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +from torch import Tensor
And this?

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    Complete
Complete?

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    # The embedding model is already initialize.
initialized

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +        embeddings_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
Let's keep consistent - either "embeddings_model" or "embedding_model"

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +from sentence_transformers import SentenceTransformer, util
Not a fan of "util" becoming a word that relates to an imported module. Maybe use "as"

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    "As an AI language model, I am unable to fulfill requests that involve sharing "
I think we can just cut this sentence after "that"

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    "I cannot provide assistance or guidance on .",
Maybe remove the last to characters

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    "I cannot provide assistance or guidance on .",
In other examples as well - probably no need for the space and the period at the end of the sentence

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    "I am prohibited from generating explicit, adult, or inappropriate content",
maybe cut after "generating".

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    "I am prohibited from generating explicit, adult, or inappropriate content",
Other examples as well, probably better to just keep the "refusal" part, and the not the specifics of the refusal, no?

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    "I am prohibited from generating explicit, adult, or inappropriate content",
Once we have some tests in its own test file - it would be great to try to find things that break these and improve accordingly.

2023-08-14 11:12 UTC, itaiMona commented on tests/test_chat_completion.py
> +    "refusal_probability": (0.18,),
I'd expect in that file to have a list of real responses, with a comment on each on what prompt for what model caused each response.

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    Given a text, return the probably that it's a refusal answer by a LLM model.
"LLM model" ~ "ATM machine"

2023-08-14 11:12 UTC, itaiMona commented on mona_openai/analysis/refusal.py
> +    # Compute the embedding for the given text.
This and the below comments seem pretty redundant to me. The code is very clear here.

2023-08-15 07:24 UTC, TalzMona commented on mona_openai/endpoints/endpoint_wrapping.py
> +    def _get_full_profainty_analysis(
I'm using the same tools we are using in our other repos. You should talk to Tzach about it.

2023-08-15 09:30 UTC, TalzMona commented on mona_openai/analysis/refusal.py
> +from huggingface_hub.utils._errors import RepositoryNotFoundError
This should be installed as part of the "sentence-transformers" I already added to the requirements.
Need to make sure it's working properly on a clean env.
Actually, when first tried to run the tests - the model didn't work properly (only on tests, on a "normal" script it worked). Only after removing Numpy and installing again - it worked. We should check how it behaves on a clean env (or/and env with an existing Numpy). Maybe we should add to the requirements file a demand for a specific Numpy version.

2023-08-23 08:31 UTC, closed without merging